/**
 * Renderer-neutral contracts for desktop agent CLIs.  These deliberately do
 * not import `src/domain/types.ts`: the Electron service is allowed to evolve
 * independently and an IPC bridge can translate these events at its boundary.
 */
export type DesktopProviderId = 'claude-code' | 'codex' | 'agy'

export type AgentMetadataValue = string | number | boolean | null
export type AgentMetadata = Readonly<Record<string, AgentMetadataValue>>

export type AgentRuntimeErrorCode =
  | 'executable-not-found'
  | 'provider-unavailable'
  | 'authentication-unavailable'
  | 'process-start-failed'
  | 'process-timeout'
  | 'process-cancelled'
  | 'process-output-limit'
  | 'process-exited'
  | 'malformed-stream-event'
  | 'provider-result-error'
  | 'provider-nonterminal-result'

export type AgentRuntimeError = {
  code: AgentRuntimeErrorCode
  message: string
  retryable: boolean
}

/**
 * Runtime errors cross into renderer code, so their text is selected solely
 * from the stable error code. Provider output, paths, prompts, and diagnostics
 * must never become user-visible error text.
 */
export function agentRuntimeErrorMessage(code: AgentRuntimeErrorCode): string {
  switch (code) {
    case 'executable-not-found': return '에이전트 실행 파일을 찾을 수 없습니다.'
    case 'provider-unavailable': return '에이전트를 잠시 사용할 수 없습니다.'
    case 'authentication-unavailable': return '에이전트 인증을 확인할 수 없습니다.'
    case 'process-start-failed': return '에이전트를 시작하지 못했습니다.'
    case 'process-timeout': return '에이전트 실행 시간이 초과되었습니다.'
    case 'process-cancelled': return '에이전트 실행이 취소되었습니다.'
    case 'process-output-limit': return '에이전트 응답이 허용된 크기를 초과했습니다.'
    case 'process-exited': return '에이전트가 완료된 응답을 반환하지 않았습니다.'
    case 'malformed-stream-event': return '에이전트 응답 형식을 확인할 수 없습니다.'
    case 'provider-result-error': return '에이전트가 요청을 처리하지 못했습니다.'
    case 'provider-nonterminal-result': return '에이전트가 완료되지 않은 상태로 종료되었습니다.'
    default: return '에이전트 오류가 발생했습니다.'
  }
}

export function normalizeAgentRuntimeError(error: AgentRuntimeError): AgentRuntimeError {
  // Rebuild the object instead of spreading provider-shaped values. This also
  // drops any unexpected diagnostic fields before the event reaches IPC.
  return { code: error.code, message: agentRuntimeErrorMessage(error.code), retryable: error.retryable }
}

type EventBase = {
  runId: string
  occurredAt: string
  providerId: DesktopProviderId
  metadata: AgentMetadata
  retryable: boolean
}

export type StartedEvent = EventBase & {
  type: 'started'
}

export type TextDeltaEvent = EventBase & {
  type: 'text-delta'
  text: string
}

export type ResultEvent = EventBase & {
  type: 'result'
  text: string
}

export type ErrorEvent = EventBase & {
  type: 'error'
  error: AgentRuntimeError
}

export type DoneEvent = EventBase & {
  type: 'done'
  outcome: 'success' | 'error' | 'cancelled'
}

/** Normalized stream produced by every provider adapter. */
export type NormalizedAgentEvent = StartedEvent | TextDeltaEvent | ResultEvent | ErrorEvent | DoneEvent

export type AgentRunOptions = {
  /** An opaque id generated by the integration layer; it is never logged. */
  runId: string
  /** Prompt content is forwarded only as an argv value and is never retained by this package. */
  prompt: string
  /** Must be an absolute workspace directory owned by the desktop app. */
  cwd: string
  signal?: AbortSignal
  timeoutMs?: number
  model?: string
  effort?: 'low' | 'medium' | 'high'
  agent?: string
  conversationId?: string
  /** Agy's documented print-mode timeout, for example `90s` or `5m`. */
  printTimeout?: string
}

export type ProviderHealth = {
  providerId: DesktopProviderId
  status: 'healthy' | 'limited' | 'failed'
  executablePath?: string
  /** True only when the no-prompt authenticated usability probe exited successfully. */
  authenticated: boolean
  checkedAt: string
  message: string
}

export interface DesktopAgentProvider {
  readonly id: DesktopProviderId
  healthCheck(): Promise<ProviderHealth>
  run(options: AgentRunOptions): AsyncIterable<NormalizedAgentEvent>
}
